# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nifty Times
tagline:          'a blog about life'
description:      'Nifty Me'
url:              https://terrib1e.github.io

author:
  name:           'Elijah Clark'
  url:            https://terrib1e.github.io

paginate:         5
paginate_path:    '/blog/page:num/'

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/terrib1e/terrib1e.github.io
