
title: Nifty Me
description: "Nifty Me"
url: "http://terrib1e.github.io"
author: EC


author-image: /img/profilepic.png
project1-image: /images/image_fun.png
project2-image: /images/flex_time.png

baseurl:   # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

#color scheme
sidebar-color: '#015870'     #those apostrophes are important
accent-color: '#f8b36d'     #those apostrophes are important

#social
linkedin: https://linkedin.com/
github: https://github.com/Terrib1e
email: mailto:niftyme@protonmail.com

#Other
analytics: UA-101230746-1
#disqus-shortname:   #Disqus comments
#google-custom-search-cx: '017575011755499056211:vwrwldvgq6s'        #Create Custom Search Engine(CSE) with google and find this ID in the code they provide.

simpleform-api-token: 5fd14849a6e9f329fc52b0d6885dfa7e

destination: ./_site
permalink: /:title/
paginate: 6
paginate_path: /page:num/

sass:
    style: compressed
    
gems: [jekyll-paginate]


