title:  "Nifty Me"
tagline: "A tale of triumph!"
description:
author:
  name: "Elijah Clark"
  github: terrib1e

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'NiftyMe'

menu:
- {name: 'Misc thoughts', file: 'facts.html'}
- {name: 'Project the projects', file: 'projects.html'}
- {name: 'Blog aka ramblin', file: 'blog.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/ghostatlas'}
- {icon: 'github', link: 'https://www.github.com/terrib1e'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/elijah-clark-29187b116/'}
- {icon: 'envelope', link: 'mailto:niftyme@protonmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
